/*
 * OpenGL ES 2.0 bindings
 *
 * Note: GLvoid* type is now treated as a string in mruby side,
 * I will write another mrbgem later which adds Array#pack and
 * String#unpack to help convert between mruby arrays and
 * native data used by OpenGL ES.
 */
#include <mruby.h>

#include <GLES2/gl2.h>

#include "mrb_gl_defs.h"

static struct RClass *mod_gl2;

FUNC_ARG_1(ActiveTexture, GLenum);
FUNC_ARG_2(AttachShader, GLuint, GLuint);
FUNC_ARG_3(BindAttribLocation, GLuint, GLuint, GLchar_p);
FUNC_ARG_2(BindBuffer, GLenum, GLuint);
FUNC_ARG_2(BindFramebuffer, GLenum, GLuint);
FUNC_ARG_2(BindRenderbuffer, GLenum, GLuint);
FUNC_ARG_2(BindTexture, GLenum, GLuint);
FUNC_ARG_4(BlendColor, GLclampf, GLclampf, GLclampf, GLclampf);
FUNC_ARG_1(BlendEquation, GLenum);
FUNC_ARG_2(BlendEquationSeparate, GLenum, GLenum);
FUNC_ARG_2(BlendFunc, GLenum, GLenum);
FUNC_ARG_4(BlendFuncSeparate, GLenum, GLenum, GLenum, GLenum);
FUNC_ARG_4(BufferData, GLenum, GLsizeiptr, GLvoid_p, GLenum);
FUNC_ARG_4(BufferSubData, GLenum, GLintptr, GLsizeiptr, GLvoid_p);
FUNC_RET_ARG_1(CheckFramebufferStatus, GLenum, GLenum);
FUNC_ARG_1(Clear, GLbitfield);
FUNC_ARG_4(ClearColor, GLclampf, GLclampf, GLclampf, GLclampf);
FUNC_ARG_1(ClearDepthf, GLclampf);
FUNC_ARG_1(ClearStencil, GLint);
FUNC_ARG_4(ColorMask, GLboolean, GLboolean, GLboolean, GLboolean);

void
mrb_mruby_gles_gem_gl2_init(mrb_state* mrb)
{
  mod_gl2 = mrb_define_module(mrb, "GL2");

  /* constants */
  MRB_ATTACH_CONST(ES_VERSION_2_0);

  MRB_ATTACH_CONST(DEPTH_BUFFER_BIT);
  MRB_ATTACH_CONST(STENCIL_BUFFER_BIT);
  MRB_ATTACH_CONST(COLOR_BUFFER_BIT);

  MRB_ATTACH_CONST(FALSE);
  MRB_ATTACH_CONST(TRUE);

  MRB_ATTACH_CONST(POINTS);
  MRB_ATTACH_CONST(LINES);
  MRB_ATTACH_CONST(LINE_LOOP);
  MRB_ATTACH_CONST(LINE_STRIP);
  MRB_ATTACH_CONST(TRIANGLES);
  MRB_ATTACH_CONST(TRIANGLE_STRIP);
  MRB_ATTACH_CONST(TRIANGLE_FAN);

  MRB_ATTACH_CONST(ZERO);
  MRB_ATTACH_CONST(ONE);
  MRB_ATTACH_CONST(SRC_COLOR);
  MRB_ATTACH_CONST(ONE_MINUS_SRC_COLOR);
  MRB_ATTACH_CONST(SRC_ALPHA);
  MRB_ATTACH_CONST(ONE_MINUS_SRC_ALPHA);
  MRB_ATTACH_CONST(DST_ALPHA);
  MRB_ATTACH_CONST(ONE_MINUS_DST_ALPHA);

  MRB_ATTACH_CONST(DST_COLOR);
  MRB_ATTACH_CONST(ONE_MINUS_DST_COLOR);
  MRB_ATTACH_CONST(SRC_ALPHA_SATURATE);

  MRB_ATTACH_CONST(FUNC_ADD);
  MRB_ATTACH_CONST(BLEND_EQUATION);
  MRB_ATTACH_CONST(BLEND_EQUATION_RGB);
  MRB_ATTACH_CONST(BLEND_EQUATION_ALPHA);

  MRB_ATTACH_CONST(FUNC_SUBTRACT);
  MRB_ATTACH_CONST(FUNC_REVERSE_SUBTRACT);

  MRB_ATTACH_CONST(BLEND_DST_RGB);
  MRB_ATTACH_CONST(BLEND_SRC_RGB);
  MRB_ATTACH_CONST(BLEND_DST_ALPHA);
  MRB_ATTACH_CONST(BLEND_SRC_ALPHA);
  MRB_ATTACH_CONST(CONSTANT_COLOR);
  MRB_ATTACH_CONST(ONE_MINUS_CONSTANT_COLOR);
  MRB_ATTACH_CONST(CONSTANT_ALPHA);
  MRB_ATTACH_CONST(ONE_MINUS_CONSTANT_ALPHA);
  MRB_ATTACH_CONST(BLEND_COLOR);

  MRB_ATTACH_CONST(ARRAY_BUFFER);
  MRB_ATTACH_CONST(ELEMENT_ARRAY_BUFFER);
  MRB_ATTACH_CONST(ARRAY_BUFFER_BINDING);
  MRB_ATTACH_CONST(ELEMENT_ARRAY_BUFFER_BINDING);

  MRB_ATTACH_CONST(STREAM_DRAW);
  MRB_ATTACH_CONST(STATIC_DRAW);
  MRB_ATTACH_CONST(DYNAMIC_DRAW);

  MRB_ATTACH_CONST(BUFFER_SIZE);
  MRB_ATTACH_CONST(BUFFER_USAGE);

  MRB_ATTACH_CONST(CURRENT_VERTEX_ATTRIB);

  MRB_ATTACH_CONST(FRONT);
  MRB_ATTACH_CONST(BACK);
  MRB_ATTACH_CONST(FRONT_AND_BACK);

  MRB_ATTACH_CONST(TEXTURE_2D);
  MRB_ATTACH_CONST(CULL_FACE);
  MRB_ATTACH_CONST(BLEND);
  MRB_ATTACH_CONST(DITHER);
  MRB_ATTACH_CONST(STENCIL_TEST);
  MRB_ATTACH_CONST(DEPTH_TEST);
  MRB_ATTACH_CONST(SCISSOR_TEST);
  MRB_ATTACH_CONST(POLYGON_OFFSET_FILL);
  MRB_ATTACH_CONST(SAMPLE_ALPHA_TO_COVERAGE);
  MRB_ATTACH_CONST(SAMPLE_COVERAGE);

  MRB_ATTACH_CONST(NO_ERROR);
  MRB_ATTACH_CONST(INVALID_ENUM);
  MRB_ATTACH_CONST(INVALID_VALUE);
  MRB_ATTACH_CONST(INVALID_OPERATION);
  MRB_ATTACH_CONST(OUT_OF_MEMORY);

  MRB_ATTACH_CONST(CW);
  MRB_ATTACH_CONST(CCW);

  MRB_ATTACH_CONST(LINE_WIDTH);
  MRB_ATTACH_CONST(ALIASED_POINT_SIZE_RANGE);
  MRB_ATTACH_CONST(ALIASED_LINE_WIDTH_RANGE);
  MRB_ATTACH_CONST(CULL_FACE_MODE);
  MRB_ATTACH_CONST(FRONT_FACE);
  MRB_ATTACH_CONST(DEPTH_RANGE);
  MRB_ATTACH_CONST(DEPTH_WRITEMASK);
  MRB_ATTACH_CONST(DEPTH_CLEAR_VALUE);
  MRB_ATTACH_CONST(DEPTH_FUNC);
  MRB_ATTACH_CONST(STENCIL_CLEAR_VALUE);
  MRB_ATTACH_CONST(STENCIL_FUNC);
  MRB_ATTACH_CONST(STENCIL_FAIL);
  MRB_ATTACH_CONST(STENCIL_PASS_DEPTH_FAIL);
  MRB_ATTACH_CONST(STENCIL_PASS_DEPTH_PASS);
  MRB_ATTACH_CONST(STENCIL_REF);
  MRB_ATTACH_CONST(STENCIL_VALUE_MASK);
  MRB_ATTACH_CONST(STENCIL_WRITEMASK);
  MRB_ATTACH_CONST(STENCIL_BACK_FUNC);
  MRB_ATTACH_CONST(STENCIL_BACK_FAIL);
  MRB_ATTACH_CONST(STENCIL_BACK_PASS_DEPTH_FAIL);
  MRB_ATTACH_CONST(STENCIL_BACK_PASS_DEPTH_PASS);
  MRB_ATTACH_CONST(STENCIL_BACK_REF);
  MRB_ATTACH_CONST(STENCIL_BACK_VALUE_MASK);
  MRB_ATTACH_CONST(STENCIL_BACK_WRITEMASK);
  MRB_ATTACH_CONST(VIEWPORT);
  MRB_ATTACH_CONST(SCISSOR_BOX);

  MRB_ATTACH_CONST(COLOR_CLEAR_VALUE);
  MRB_ATTACH_CONST(COLOR_WRITEMASK);
  MRB_ATTACH_CONST(UNPACK_ALIGNMENT);
  MRB_ATTACH_CONST(PACK_ALIGNMENT);
  MRB_ATTACH_CONST(MAX_TEXTURE_SIZE);
  MRB_ATTACH_CONST(MAX_VIEWPORT_DIMS);
  MRB_ATTACH_CONST(SUBPIXEL_BITS);
  MRB_ATTACH_CONST(RED_BITS);
  MRB_ATTACH_CONST(GREEN_BITS);
  MRB_ATTACH_CONST(BLUE_BITS);
  MRB_ATTACH_CONST(ALPHA_BITS);
  MRB_ATTACH_CONST(DEPTH_BITS);
  MRB_ATTACH_CONST(STENCIL_BITS);
  MRB_ATTACH_CONST(POLYGON_OFFSET_UNITS);

  MRB_ATTACH_CONST(POLYGON_OFFSET_FACTOR);
  MRB_ATTACH_CONST(TEXTURE_BINDING_2D);
  MRB_ATTACH_CONST(SAMPLE_BUFFERS);
  MRB_ATTACH_CONST(SAMPLES);
  MRB_ATTACH_CONST(SAMPLE_COVERAGE_VALUE);
  MRB_ATTACH_CONST(SAMPLE_COVERAGE_INVERT);

  MRB_ATTACH_CONST(NUM_COMPRESSED_TEXTURE_FORMATS);
  MRB_ATTACH_CONST(COMPRESSED_TEXTURE_FORMATS);

  MRB_ATTACH_CONST(DONT_CARE);
  MRB_ATTACH_CONST(FASTEST);
  MRB_ATTACH_CONST(NICEST);

  MRB_ATTACH_CONST(GENERATE_MIPMAP_HINT);

  MRB_ATTACH_CONST(BYTE);
  MRB_ATTACH_CONST(UNSIGNED_BYTE);
  MRB_ATTACH_CONST(SHORT);
  MRB_ATTACH_CONST(UNSIGNED_SHORT);
  MRB_ATTACH_CONST(INT);
  MRB_ATTACH_CONST(UNSIGNED_INT);
  MRB_ATTACH_CONST(FLOAT);
  MRB_ATTACH_CONST(FIXED);

  MRB_ATTACH_CONST(DEPTH_COMPONENT);
  MRB_ATTACH_CONST(ALPHA);
  MRB_ATTACH_CONST(RGB);
  MRB_ATTACH_CONST(RGBA);
  MRB_ATTACH_CONST(LUMINANCE);
  MRB_ATTACH_CONST(LUMINANCE_ALPHA);

  MRB_ATTACH_CONST(UNSIGNED_SHORT_4_4_4_4);
  MRB_ATTACH_CONST(UNSIGNED_SHORT_5_5_5_1);
  MRB_ATTACH_CONST(UNSIGNED_SHORT_5_6_5);

  MRB_ATTACH_CONST(FRAGMENT_SHADER);
  MRB_ATTACH_CONST(VERTEX_SHADER);
  MRB_ATTACH_CONST(MAX_VERTEX_ATTRIBS);
  MRB_ATTACH_CONST(MAX_VERTEX_UNIFORM_VECTORS);
  MRB_ATTACH_CONST(MAX_VARYING_VECTORS);
  MRB_ATTACH_CONST(MAX_COMBINED_TEXTURE_IMAGE_UNITS);
  MRB_ATTACH_CONST(MAX_VERTEX_TEXTURE_IMAGE_UNITS);
  MRB_ATTACH_CONST(MAX_TEXTURE_IMAGE_UNITS);
  MRB_ATTACH_CONST(MAX_FRAGMENT_UNIFORM_VECTORS);
  MRB_ATTACH_CONST(SHADER_TYPE);
  MRB_ATTACH_CONST(DELETE_STATUS);
  MRB_ATTACH_CONST(LINK_STATUS);
  MRB_ATTACH_CONST(VALIDATE_STATUS);
  MRB_ATTACH_CONST(ATTACHED_SHADERS);
  MRB_ATTACH_CONST(ACTIVE_UNIFORMS);
  MRB_ATTACH_CONST(ACTIVE_UNIFORM_MAX_LENGTH);
  MRB_ATTACH_CONST(ACTIVE_ATTRIBUTES);
  MRB_ATTACH_CONST(ACTIVE_ATTRIBUTE_MAX_LENGTH);
  MRB_ATTACH_CONST(SHADING_LANGUAGE_VERSION);
  MRB_ATTACH_CONST(CURRENT_PROGRAM);

  MRB_ATTACH_CONST(NEVER);
  MRB_ATTACH_CONST(LESS);
  MRB_ATTACH_CONST(EQUAL);
  MRB_ATTACH_CONST(LEQUAL);
  MRB_ATTACH_CONST(GREATER);
  MRB_ATTACH_CONST(NOTEQUAL);
  MRB_ATTACH_CONST(GEQUAL);
  MRB_ATTACH_CONST(ALWAYS);

  MRB_ATTACH_CONST(KEEP);
  MRB_ATTACH_CONST(REPLACE);
  MRB_ATTACH_CONST(INCR);
  MRB_ATTACH_CONST(DECR);
  MRB_ATTACH_CONST(INVERT);
  MRB_ATTACH_CONST(INCR_WRAP);
  MRB_ATTACH_CONST(DECR_WRAP);

  MRB_ATTACH_CONST(VENDOR);
  MRB_ATTACH_CONST(RENDERER);
  MRB_ATTACH_CONST(VERSION);
  MRB_ATTACH_CONST(EXTENSIONS);

  MRB_ATTACH_CONST(NEAREST);
  MRB_ATTACH_CONST(LINEAR);

  MRB_ATTACH_CONST(NEAREST_MIPMAP_NEAREST);
  MRB_ATTACH_CONST(LINEAR_MIPMAP_NEAREST);
  MRB_ATTACH_CONST(NEAREST_MIPMAP_LINEAR);
  MRB_ATTACH_CONST(LINEAR_MIPMAP_LINEAR);

  MRB_ATTACH_CONST(TEXTURE_MAG_FILTER);
  MRB_ATTACH_CONST(TEXTURE_MIN_FILTER);
  MRB_ATTACH_CONST(TEXTURE_WRAP_S);
  MRB_ATTACH_CONST(TEXTURE_WRAP_T);

  MRB_ATTACH_CONST(TEXTURE);

  MRB_ATTACH_CONST(TEXTURE_CUBE_MAP);
  MRB_ATTACH_CONST(TEXTURE_BINDING_CUBE_MAP);
  MRB_ATTACH_CONST(TEXTURE_CUBE_MAP_POSITIVE_X);
  MRB_ATTACH_CONST(TEXTURE_CUBE_MAP_NEGATIVE_X);
  MRB_ATTACH_CONST(TEXTURE_CUBE_MAP_POSITIVE_Y);
  MRB_ATTACH_CONST(TEXTURE_CUBE_MAP_NEGATIVE_Y);
  MRB_ATTACH_CONST(TEXTURE_CUBE_MAP_POSITIVE_Z);
  MRB_ATTACH_CONST(TEXTURE_CUBE_MAP_NEGATIVE_Z);
  MRB_ATTACH_CONST(MAX_CUBE_MAP_TEXTURE_SIZE);

  MRB_ATTACH_CONST(TEXTURE0);
  MRB_ATTACH_CONST(TEXTURE1);
  MRB_ATTACH_CONST(TEXTURE2);
  MRB_ATTACH_CONST(TEXTURE3);
  MRB_ATTACH_CONST(TEXTURE4);
  MRB_ATTACH_CONST(TEXTURE5);
  MRB_ATTACH_CONST(TEXTURE6);
  MRB_ATTACH_CONST(TEXTURE7);
  MRB_ATTACH_CONST(TEXTURE8);
  MRB_ATTACH_CONST(TEXTURE9);
  MRB_ATTACH_CONST(TEXTURE10);
  MRB_ATTACH_CONST(TEXTURE11);
  MRB_ATTACH_CONST(TEXTURE12);
  MRB_ATTACH_CONST(TEXTURE13);
  MRB_ATTACH_CONST(TEXTURE14);
  MRB_ATTACH_CONST(TEXTURE15);
  MRB_ATTACH_CONST(TEXTURE16);
  MRB_ATTACH_CONST(TEXTURE17);
  MRB_ATTACH_CONST(TEXTURE18);
  MRB_ATTACH_CONST(TEXTURE19);
  MRB_ATTACH_CONST(TEXTURE20);
  MRB_ATTACH_CONST(TEXTURE21);
  MRB_ATTACH_CONST(TEXTURE22);
  MRB_ATTACH_CONST(TEXTURE23);
  MRB_ATTACH_CONST(TEXTURE24);
  MRB_ATTACH_CONST(TEXTURE25);
  MRB_ATTACH_CONST(TEXTURE26);
  MRB_ATTACH_CONST(TEXTURE27);
  MRB_ATTACH_CONST(TEXTURE28);
  MRB_ATTACH_CONST(TEXTURE29);
  MRB_ATTACH_CONST(TEXTURE30);
  MRB_ATTACH_CONST(TEXTURE31);
  MRB_ATTACH_CONST(ACTIVE_TEXTURE);

  MRB_ATTACH_CONST(REPEAT);
  MRB_ATTACH_CONST(CLAMP_TO_EDGE);
  MRB_ATTACH_CONST(MIRRORED_REPEAT);

  MRB_ATTACH_CONST(FLOAT_VEC2);
  MRB_ATTACH_CONST(FLOAT_VEC3);
  MRB_ATTACH_CONST(FLOAT_VEC4);
  MRB_ATTACH_CONST(INT_VEC2);
  MRB_ATTACH_CONST(INT_VEC3);
  MRB_ATTACH_CONST(INT_VEC4);
  MRB_ATTACH_CONST(BOOL);
  MRB_ATTACH_CONST(BOOL_VEC2);
  MRB_ATTACH_CONST(BOOL_VEC3);
  MRB_ATTACH_CONST(BOOL_VEC4);
  MRB_ATTACH_CONST(FLOAT_MAT2);
  MRB_ATTACH_CONST(FLOAT_MAT3);
  MRB_ATTACH_CONST(FLOAT_MAT4);
  MRB_ATTACH_CONST(SAMPLER_2D);
  MRB_ATTACH_CONST(SAMPLER_CUBE);

  MRB_ATTACH_CONST(VERTEX_ATTRIB_ARRAY_ENABLED);
  MRB_ATTACH_CONST(VERTEX_ATTRIB_ARRAY_SIZE);
  MRB_ATTACH_CONST(VERTEX_ATTRIB_ARRAY_STRIDE);
  MRB_ATTACH_CONST(VERTEX_ATTRIB_ARRAY_TYPE);
  MRB_ATTACH_CONST(VERTEX_ATTRIB_ARRAY_NORMALIZED);
  MRB_ATTACH_CONST(VERTEX_ATTRIB_ARRAY_POINTER);
  MRB_ATTACH_CONST(VERTEX_ATTRIB_ARRAY_BUFFER_BINDING);

  MRB_ATTACH_CONST(IMPLEMENTATION_COLOR_READ_TYPE);
  MRB_ATTACH_CONST(IMPLEMENTATION_COLOR_READ_FORMAT);

  MRB_ATTACH_CONST(COMPILE_STATUS);
  MRB_ATTACH_CONST(INFO_LOG_LENGTH);
  MRB_ATTACH_CONST(SHADER_SOURCE_LENGTH);
  MRB_ATTACH_CONST(SHADER_COMPILER);

  MRB_ATTACH_CONST(SHADER_BINARY_FORMATS);
  MRB_ATTACH_CONST(NUM_SHADER_BINARY_FORMATS);

  MRB_ATTACH_CONST(LOW_FLOAT);
  MRB_ATTACH_CONST(MEDIUM_FLOAT);
  MRB_ATTACH_CONST(HIGH_FLOAT);
  MRB_ATTACH_CONST(LOW_INT);
  MRB_ATTACH_CONST(MEDIUM_INT);
  MRB_ATTACH_CONST(HIGH_INT);

  MRB_ATTACH_CONST(FRAMEBUFFER);
  MRB_ATTACH_CONST(RENDERBUFFER);

  MRB_ATTACH_CONST(RGBA4);
  MRB_ATTACH_CONST(RGB5_A1);
  MRB_ATTACH_CONST(RGB565);
  MRB_ATTACH_CONST(DEPTH_COMPONENT16);
  MRB_ATTACH_CONST(STENCIL_INDEX);
  MRB_ATTACH_CONST(STENCIL_INDEX8);

  MRB_ATTACH_CONST(RENDERBUFFER_WIDTH);
  MRB_ATTACH_CONST(RENDERBUFFER_HEIGHT);
  MRB_ATTACH_CONST(RENDERBUFFER_INTERNAL_FORMAT);
  MRB_ATTACH_CONST(RENDERBUFFER_RED_SIZE);
  MRB_ATTACH_CONST(RENDERBUFFER_GREEN_SIZE);
  MRB_ATTACH_CONST(RENDERBUFFER_BLUE_SIZE);
  MRB_ATTACH_CONST(RENDERBUFFER_ALPHA_SIZE);
  MRB_ATTACH_CONST(RENDERBUFFER_DEPTH_SIZE);
  MRB_ATTACH_CONST(RENDERBUFFER_STENCIL_SIZE);

  MRB_ATTACH_CONST(FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE);
  MRB_ATTACH_CONST(FRAMEBUFFER_ATTACHMENT_OBJECT_NAME);
  MRB_ATTACH_CONST(FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL);
  MRB_ATTACH_CONST(FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE);

  MRB_ATTACH_CONST(COLOR_ATTACHMENT0);
  MRB_ATTACH_CONST(DEPTH_ATTACHMENT);
  MRB_ATTACH_CONST(STENCIL_ATTACHMENT);

  MRB_ATTACH_CONST(NONE);

  MRB_ATTACH_CONST(FRAMEBUFFER_COMPLETE);
  MRB_ATTACH_CONST(FRAMEBUFFER_INCOMPLETE_ATTACHMENT);
  MRB_ATTACH_CONST(FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT);
  MRB_ATTACH_CONST(FRAMEBUFFER_INCOMPLETE_DIMENSIONS);
  MRB_ATTACH_CONST(FRAMEBUFFER_UNSUPPORTED);

  MRB_ATTACH_CONST(FRAMEBUFFER_BINDING);
  MRB_ATTACH_CONST(RENDERBUFFER_BINDING);
  MRB_ATTACH_CONST(MAX_RENDERBUFFER_SIZE);

  MRB_ATTACH_CONST(INVALID_FRAMEBUFFER_OPERATION);

  /* GL core functions */
  MRB_ATTACH_FUNC(ActiveTexture, 1);
  MRB_ATTACH_FUNC(AttachShader, 2);
  MRB_ATTACH_FUNC(BindAttribLocation, 3);
  MRB_ATTACH_FUNC(BindBuffer, 2);
  MRB_ATTACH_FUNC(BindFramebuffer, 2);
  MRB_ATTACH_FUNC(BindRenderbuffer, 2);
  MRB_ATTACH_FUNC(BindTexture, 2);
  MRB_ATTACH_FUNC(BlendColor, 4);
  MRB_ATTACH_FUNC(BlendEquation, 1);
  MRB_ATTACH_FUNC(BlendEquationSeparate, 2);
  MRB_ATTACH_FUNC(BlendFunc, 2);
  MRB_ATTACH_FUNC(BlendFuncSeparate, 4);
  MRB_ATTACH_FUNC(BufferData, 4);
  MRB_ATTACH_FUNC(BufferSubData, 4);
  MRB_ATTACH_FUNC(CheckFramebufferStatus, 1);
  MRB_ATTACH_FUNC(Clear, 1);
  MRB_ATTACH_FUNC(ClearColor, 4);
  MRB_ATTACH_FUNC(ClearDepthf, 1);
  MRB_ATTACH_FUNC(ClearStencil, 1);
  MRB_ATTACH_FUNC(ColorMask, 4);
}
