/*
 * OpenGL ES 2.0 bindings
 *
 * Note: GLvoid* type is now treated as a string in mruby side,
 * I will write another mrbgem later which adds Array#pack and
 * String#unpack to help convert between mruby arrays and
 * native data used by OpenGL ES.
 */
#include <mruby.h>
#include <mruby/array.h>

#include <GLES2/gl2.h>

#include "mrb_gl_defs.h"

static struct RClass *mod_gl2;

DEF_CONVERT_UTILS(GLuint);

FUNC_ARG_1(ActiveTexture, GLenum);
FUNC_ARG_2(AttachShader, GLuint, GLuint);
FUNC_ARG_3(BindAttribLocation, GLuint, GLuint, GLchar_p);
FUNC_ARG_2(BindBuffer, GLenum, GLuint);
FUNC_ARG_2(BindFramebuffer, GLenum, GLuint);
FUNC_ARG_2(BindRenderbuffer, GLenum, GLuint);
FUNC_ARG_2(BindTexture, GLenum, GLuint);
FUNC_ARG_4(BlendColor, GLclampf, GLclampf, GLclampf, GLclampf);
FUNC_ARG_1(BlendEquation, GLenum);
FUNC_ARG_2(BlendEquationSeparate, GLenum, GLenum);
FUNC_ARG_2(BlendFunc, GLenum, GLenum);
FUNC_ARG_4(BlendFuncSeparate, GLenum, GLenum, GLenum, GLenum);
FUNC_ARG_4(BufferData, GLenum, GLsizeiptr, GLvoid_p, GLenum);
FUNC_ARG_4(BufferSubData, GLenum, GLintptr, GLsizeiptr, GLvoid_p);
FUNC_RET_ARG_1(CheckFramebufferStatus, GLenum, GLenum);
FUNC_ARG_1(Clear, GLbitfield);
FUNC_ARG_4(ClearColor, GLclampf, GLclampf, GLclampf, GLclampf);
FUNC_ARG_1(ClearDepthf, GLclampf);
FUNC_ARG_1(ClearStencil, GLint);
FUNC_ARG_4(ColorMask, GLboolean, GLboolean, GLboolean, GLboolean);
FUNC_ARG_1(CompileShader, GLuint);
FUNC_ARG_8(CompressedTexImage2D, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, GLvoid_p);
FUNC_ARG_9(CompressedTexSubImage2D, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, GLvoid_p);
FUNC_ARG_8(CopyTexImage2D, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint);
FUNC_ARG_8(CopyTexSubImage2D, GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei);
FUNC_RET_ARG_0(CreateProgram, GLuint);
FUNC_RET_ARG_1(CreateShader, GLuint, GLenum);
FUNC_ARG_1(CullFace, GLenum);
FUNC_ARG_2(DeleteBuffers, GLsizei, GLuint_arr);
FUNC_ARG_2(DeleteFramebuffers, GLsizei, GLuint_arr);
FUNC_ARG_1(DeleteProgram, GLuint);
FUNC_ARG_2(DeleteRenderbuffers, GLsizei, GLuint_arr);
FUNC_ARG_1(DeleteShader, GLuint);
FUNC_ARG_2(DeleteTextures, GLsizei, GLuint_arr);
FUNC_ARG_1(DepthFunc, GLenum);
FUNC_ARG_1(DepthMask, GLboolean);
FUNC_ARG_2(DepthRangef, GLclampf, GLclampf);
FUNC_ARG_2(DetachShader, GLuint, GLuint);
FUNC_ARG_1(Disable, GLenum);
FUNC_ARG_1(DisableVertexAttribArray, GLuint);
FUNC_ARG_3(DrawArrays, GLenum, GLint, GLsizei);
FUNC_ARG_4(DrawElements, GLenum, GLsizei, GLenum, GLvoid_p);
FUNC_ARG_1(Enable, GLenum);
FUNC_ARG_1(EnableVertexAttribArray, GLuint);
FUNC_ARG_0(Finish);
FUNC_ARG_0(Flush);
FUNC_ARG_4(FramebufferRenderbuffer, GLenum, GLenum, GLenum, GLuint);
FUNC_ARG_5(FramebufferTexture2D, GLenum, GLenum, GLenum, GLuint, GLint);
FUNC_ARG_1(FrontFace, GLenum);
FUNC_ARG_2(GenBuffers, GLsizei, GLuint_arr_ret);
FUNC_ARG_1(GenerateMipmap, GLenum);
FUNC_ARG_2(GenFramebuffers, GLsizei, GLuint_arr_ret);
FUNC_ARG_2(GenRenderbuffers, GLsizei, GLuint_arr_ret);
FUNC_ARG_2(GenTextures, GLsizei, GLuint_arr_ret);

/* TODO: revisit all the glGet* functions, see we can refactor them another way. */
GET_ACTIVE_FUNC(Attrib);
GET_ACTIVE_FUNC(Uniform);

FUNC_ARG_2(Hint, GLenum, GLenum);
FUNC_RET_ARG_1(IsBuffer, GLboolean, GLuint);
FUNC_RET_ARG_1(IsEnabled, GLboolean, GLenum);
FUNC_RET_ARG_1(IsFramebuffer, GLboolean, GLuint);
FUNC_RET_ARG_1(IsProgram, GLboolean, GLuint);
FUNC_RET_ARG_1(IsRenderbuffer, GLboolean, GLuint);
FUNC_RET_ARG_1(IsShader, GLboolean, GLuint);
FUNC_RET_ARG_1(IsTexture, GLboolean, GLuint);
FUNC_ARG_1(LineWidth, GLfloat);
FUNC_ARG_1(LinkProgram, GLuint);
FUNC_ARG_2(PixelStorei, GLenum, GLint);
FUNC_ARG_2(PolygonOffset, GLfloat, GLfloat);
FUNC_ARG_0(ReleaseShaderCompiler);
FUNC_ARG_4(RenderbufferStorage, GLenum, GLenum, GLsizei, GLsizei);

void
mrb_mruby_gles_gem_gl2_init(mrb_state* mrb)
{
  mod_gl2 = mrb_define_module(mrb, "GL2");

  /* constants */
  MRB_ATTACH_CONST(ES_VERSION_2_0);

  MRB_ATTACH_CONST(DEPTH_BUFFER_BIT);
  MRB_ATTACH_CONST(STENCIL_BUFFER_BIT);
  MRB_ATTACH_CONST(COLOR_BUFFER_BIT);

  MRB_ATTACH_CONST(FALSE);
  MRB_ATTACH_CONST(TRUE);

  MRB_ATTACH_CONST(POINTS);
  MRB_ATTACH_CONST(LINES);
  MRB_ATTACH_CONST(LINE_LOOP);
  MRB_ATTACH_CONST(LINE_STRIP);
  MRB_ATTACH_CONST(TRIANGLES);
  MRB_ATTACH_CONST(TRIANGLE_STRIP);
  MRB_ATTACH_CONST(TRIANGLE_FAN);

  MRB_ATTACH_CONST(ZERO);
  MRB_ATTACH_CONST(ONE);
  MRB_ATTACH_CONST(SRC_COLOR);
  MRB_ATTACH_CONST(ONE_MINUS_SRC_COLOR);
  MRB_ATTACH_CONST(SRC_ALPHA);
  MRB_ATTACH_CONST(ONE_MINUS_SRC_ALPHA);
  MRB_ATTACH_CONST(DST_ALPHA);
  MRB_ATTACH_CONST(ONE_MINUS_DST_ALPHA);

  MRB_ATTACH_CONST(DST_COLOR);
  MRB_ATTACH_CONST(ONE_MINUS_DST_COLOR);
  MRB_ATTACH_CONST(SRC_ALPHA_SATURATE);

  MRB_ATTACH_CONST(FUNC_ADD);
  MRB_ATTACH_CONST(BLEND_EQUATION);
  MRB_ATTACH_CONST(BLEND_EQUATION_RGB);
  MRB_ATTACH_CONST(BLEND_EQUATION_ALPHA);

  MRB_ATTACH_CONST(FUNC_SUBTRACT);
  MRB_ATTACH_CONST(FUNC_REVERSE_SUBTRACT);

  MRB_ATTACH_CONST(BLEND_DST_RGB);
  MRB_ATTACH_CONST(BLEND_SRC_RGB);
  MRB_ATTACH_CONST(BLEND_DST_ALPHA);
  MRB_ATTACH_CONST(BLEND_SRC_ALPHA);
  MRB_ATTACH_CONST(CONSTANT_COLOR);
  MRB_ATTACH_CONST(ONE_MINUS_CONSTANT_COLOR);
  MRB_ATTACH_CONST(CONSTANT_ALPHA);
  MRB_ATTACH_CONST(ONE_MINUS_CONSTANT_ALPHA);
  MRB_ATTACH_CONST(BLEND_COLOR);

  MRB_ATTACH_CONST(ARRAY_BUFFER);
  MRB_ATTACH_CONST(ELEMENT_ARRAY_BUFFER);
  MRB_ATTACH_CONST(ARRAY_BUFFER_BINDING);
  MRB_ATTACH_CONST(ELEMENT_ARRAY_BUFFER_BINDING);

  MRB_ATTACH_CONST(STREAM_DRAW);
  MRB_ATTACH_CONST(STATIC_DRAW);
  MRB_ATTACH_CONST(DYNAMIC_DRAW);

  MRB_ATTACH_CONST(BUFFER_SIZE);
  MRB_ATTACH_CONST(BUFFER_USAGE);

  MRB_ATTACH_CONST(CURRENT_VERTEX_ATTRIB);

  MRB_ATTACH_CONST(FRONT);
  MRB_ATTACH_CONST(BACK);
  MRB_ATTACH_CONST(FRONT_AND_BACK);

  MRB_ATTACH_CONST(TEXTURE_2D);
  MRB_ATTACH_CONST(CULL_FACE);
  MRB_ATTACH_CONST(BLEND);
  MRB_ATTACH_CONST(DITHER);
  MRB_ATTACH_CONST(STENCIL_TEST);
  MRB_ATTACH_CONST(DEPTH_TEST);
  MRB_ATTACH_CONST(SCISSOR_TEST);
  MRB_ATTACH_CONST(POLYGON_OFFSET_FILL);
  MRB_ATTACH_CONST(SAMPLE_ALPHA_TO_COVERAGE);
  MRB_ATTACH_CONST(SAMPLE_COVERAGE);

  MRB_ATTACH_CONST(NO_ERROR);
  MRB_ATTACH_CONST(INVALID_ENUM);
  MRB_ATTACH_CONST(INVALID_VALUE);
  MRB_ATTACH_CONST(INVALID_OPERATION);
  MRB_ATTACH_CONST(OUT_OF_MEMORY);

  MRB_ATTACH_CONST(CW);
  MRB_ATTACH_CONST(CCW);

  MRB_ATTACH_CONST(LINE_WIDTH);
  MRB_ATTACH_CONST(ALIASED_POINT_SIZE_RANGE);
  MRB_ATTACH_CONST(ALIASED_LINE_WIDTH_RANGE);
  MRB_ATTACH_CONST(CULL_FACE_MODE);
  MRB_ATTACH_CONST(FRONT_FACE);
  MRB_ATTACH_CONST(DEPTH_RANGE);
  MRB_ATTACH_CONST(DEPTH_WRITEMASK);
  MRB_ATTACH_CONST(DEPTH_CLEAR_VALUE);
  MRB_ATTACH_CONST(DEPTH_FUNC);
  MRB_ATTACH_CONST(STENCIL_CLEAR_VALUE);
  MRB_ATTACH_CONST(STENCIL_FUNC);
  MRB_ATTACH_CONST(STENCIL_FAIL);
  MRB_ATTACH_CONST(STENCIL_PASS_DEPTH_FAIL);
  MRB_ATTACH_CONST(STENCIL_PASS_DEPTH_PASS);
  MRB_ATTACH_CONST(STENCIL_REF);
  MRB_ATTACH_CONST(STENCIL_VALUE_MASK);
  MRB_ATTACH_CONST(STENCIL_WRITEMASK);
  MRB_ATTACH_CONST(STENCIL_BACK_FUNC);
  MRB_ATTACH_CONST(STENCIL_BACK_FAIL);
  MRB_ATTACH_CONST(STENCIL_BACK_PASS_DEPTH_FAIL);
  MRB_ATTACH_CONST(STENCIL_BACK_PASS_DEPTH_PASS);
  MRB_ATTACH_CONST(STENCIL_BACK_REF);
  MRB_ATTACH_CONST(STENCIL_BACK_VALUE_MASK);
  MRB_ATTACH_CONST(STENCIL_BACK_WRITEMASK);
  MRB_ATTACH_CONST(VIEWPORT);
  MRB_ATTACH_CONST(SCISSOR_BOX);

  MRB_ATTACH_CONST(COLOR_CLEAR_VALUE);
  MRB_ATTACH_CONST(COLOR_WRITEMASK);
  MRB_ATTACH_CONST(UNPACK_ALIGNMENT);
  MRB_ATTACH_CONST(PACK_ALIGNMENT);
  MRB_ATTACH_CONST(MAX_TEXTURE_SIZE);
  MRB_ATTACH_CONST(MAX_VIEWPORT_DIMS);
  MRB_ATTACH_CONST(SUBPIXEL_BITS);
  MRB_ATTACH_CONST(RED_BITS);
  MRB_ATTACH_CONST(GREEN_BITS);
  MRB_ATTACH_CONST(BLUE_BITS);
  MRB_ATTACH_CONST(ALPHA_BITS);
  MRB_ATTACH_CONST(DEPTH_BITS);
  MRB_ATTACH_CONST(STENCIL_BITS);
  MRB_ATTACH_CONST(POLYGON_OFFSET_UNITS);

  MRB_ATTACH_CONST(POLYGON_OFFSET_FACTOR);
  MRB_ATTACH_CONST(TEXTURE_BINDING_2D);
  MRB_ATTACH_CONST(SAMPLE_BUFFERS);
  MRB_ATTACH_CONST(SAMPLES);
  MRB_ATTACH_CONST(SAMPLE_COVERAGE_VALUE);
  MRB_ATTACH_CONST(SAMPLE_COVERAGE_INVERT);

  MRB_ATTACH_CONST(NUM_COMPRESSED_TEXTURE_FORMATS);
  MRB_ATTACH_CONST(COMPRESSED_TEXTURE_FORMATS);

  MRB_ATTACH_CONST(DONT_CARE);
  MRB_ATTACH_CONST(FASTEST);
  MRB_ATTACH_CONST(NICEST);

  MRB_ATTACH_CONST(GENERATE_MIPMAP_HINT);

  MRB_ATTACH_CONST(BYTE);
  MRB_ATTACH_CONST(UNSIGNED_BYTE);
  MRB_ATTACH_CONST(SHORT);
  MRB_ATTACH_CONST(UNSIGNED_SHORT);
  MRB_ATTACH_CONST(INT);
  MRB_ATTACH_CONST(UNSIGNED_INT);
  MRB_ATTACH_CONST(FLOAT);
  MRB_ATTACH_CONST(FIXED);

  MRB_ATTACH_CONST(DEPTH_COMPONENT);
  MRB_ATTACH_CONST(ALPHA);
  MRB_ATTACH_CONST(RGB);
  MRB_ATTACH_CONST(RGBA);
  MRB_ATTACH_CONST(LUMINANCE);
  MRB_ATTACH_CONST(LUMINANCE_ALPHA);

  MRB_ATTACH_CONST(UNSIGNED_SHORT_4_4_4_4);
  MRB_ATTACH_CONST(UNSIGNED_SHORT_5_5_5_1);
  MRB_ATTACH_CONST(UNSIGNED_SHORT_5_6_5);

  MRB_ATTACH_CONST(FRAGMENT_SHADER);
  MRB_ATTACH_CONST(VERTEX_SHADER);
  MRB_ATTACH_CONST(MAX_VERTEX_ATTRIBS);
  MRB_ATTACH_CONST(MAX_VERTEX_UNIFORM_VECTORS);
  MRB_ATTACH_CONST(MAX_VARYING_VECTORS);
  MRB_ATTACH_CONST(MAX_COMBINED_TEXTURE_IMAGE_UNITS);
  MRB_ATTACH_CONST(MAX_VERTEX_TEXTURE_IMAGE_UNITS);
  MRB_ATTACH_CONST(MAX_TEXTURE_IMAGE_UNITS);
  MRB_ATTACH_CONST(MAX_FRAGMENT_UNIFORM_VECTORS);
  MRB_ATTACH_CONST(SHADER_TYPE);
  MRB_ATTACH_CONST(DELETE_STATUS);
  MRB_ATTACH_CONST(LINK_STATUS);
  MRB_ATTACH_CONST(VALIDATE_STATUS);
  MRB_ATTACH_CONST(ATTACHED_SHADERS);
  MRB_ATTACH_CONST(ACTIVE_UNIFORMS);
  MRB_ATTACH_CONST(ACTIVE_UNIFORM_MAX_LENGTH);
  MRB_ATTACH_CONST(ACTIVE_ATTRIBUTES);
  MRB_ATTACH_CONST(ACTIVE_ATTRIBUTE_MAX_LENGTH);
  MRB_ATTACH_CONST(SHADING_LANGUAGE_VERSION);
  MRB_ATTACH_CONST(CURRENT_PROGRAM);

  MRB_ATTACH_CONST(NEVER);
  MRB_ATTACH_CONST(LESS);
  MRB_ATTACH_CONST(EQUAL);
  MRB_ATTACH_CONST(LEQUAL);
  MRB_ATTACH_CONST(GREATER);
  MRB_ATTACH_CONST(NOTEQUAL);
  MRB_ATTACH_CONST(GEQUAL);
  MRB_ATTACH_CONST(ALWAYS);

  MRB_ATTACH_CONST(KEEP);
  MRB_ATTACH_CONST(REPLACE);
  MRB_ATTACH_CONST(INCR);
  MRB_ATTACH_CONST(DECR);
  MRB_ATTACH_CONST(INVERT);
  MRB_ATTACH_CONST(INCR_WRAP);
  MRB_ATTACH_CONST(DECR_WRAP);

  MRB_ATTACH_CONST(VENDOR);
  MRB_ATTACH_CONST(RENDERER);
  MRB_ATTACH_CONST(VERSION);
  MRB_ATTACH_CONST(EXTENSIONS);

  MRB_ATTACH_CONST(NEAREST);
  MRB_ATTACH_CONST(LINEAR);

  MRB_ATTACH_CONST(NEAREST_MIPMAP_NEAREST);
  MRB_ATTACH_CONST(LINEAR_MIPMAP_NEAREST);
  MRB_ATTACH_CONST(NEAREST_MIPMAP_LINEAR);
  MRB_ATTACH_CONST(LINEAR_MIPMAP_LINEAR);

  MRB_ATTACH_CONST(TEXTURE_MAG_FILTER);
  MRB_ATTACH_CONST(TEXTURE_MIN_FILTER);
  MRB_ATTACH_CONST(TEXTURE_WRAP_S);
  MRB_ATTACH_CONST(TEXTURE_WRAP_T);

  MRB_ATTACH_CONST(TEXTURE);

  MRB_ATTACH_CONST(TEXTURE_CUBE_MAP);
  MRB_ATTACH_CONST(TEXTURE_BINDING_CUBE_MAP);
  MRB_ATTACH_CONST(TEXTURE_CUBE_MAP_POSITIVE_X);
  MRB_ATTACH_CONST(TEXTURE_CUBE_MAP_NEGATIVE_X);
  MRB_ATTACH_CONST(TEXTURE_CUBE_MAP_POSITIVE_Y);
  MRB_ATTACH_CONST(TEXTURE_CUBE_MAP_NEGATIVE_Y);
  MRB_ATTACH_CONST(TEXTURE_CUBE_MAP_POSITIVE_Z);
  MRB_ATTACH_CONST(TEXTURE_CUBE_MAP_NEGATIVE_Z);
  MRB_ATTACH_CONST(MAX_CUBE_MAP_TEXTURE_SIZE);

  MRB_ATTACH_CONST(TEXTURE0);
  MRB_ATTACH_CONST(TEXTURE1);
  MRB_ATTACH_CONST(TEXTURE2);
  MRB_ATTACH_CONST(TEXTURE3);
  MRB_ATTACH_CONST(TEXTURE4);
  MRB_ATTACH_CONST(TEXTURE5);
  MRB_ATTACH_CONST(TEXTURE6);
  MRB_ATTACH_CONST(TEXTURE7);
  MRB_ATTACH_CONST(TEXTURE8);
  MRB_ATTACH_CONST(TEXTURE9);
  MRB_ATTACH_CONST(TEXTURE10);
  MRB_ATTACH_CONST(TEXTURE11);
  MRB_ATTACH_CONST(TEXTURE12);
  MRB_ATTACH_CONST(TEXTURE13);
  MRB_ATTACH_CONST(TEXTURE14);
  MRB_ATTACH_CONST(TEXTURE15);
  MRB_ATTACH_CONST(TEXTURE16);
  MRB_ATTACH_CONST(TEXTURE17);
  MRB_ATTACH_CONST(TEXTURE18);
  MRB_ATTACH_CONST(TEXTURE19);
  MRB_ATTACH_CONST(TEXTURE20);
  MRB_ATTACH_CONST(TEXTURE21);
  MRB_ATTACH_CONST(TEXTURE22);
  MRB_ATTACH_CONST(TEXTURE23);
  MRB_ATTACH_CONST(TEXTURE24);
  MRB_ATTACH_CONST(TEXTURE25);
  MRB_ATTACH_CONST(TEXTURE26);
  MRB_ATTACH_CONST(TEXTURE27);
  MRB_ATTACH_CONST(TEXTURE28);
  MRB_ATTACH_CONST(TEXTURE29);
  MRB_ATTACH_CONST(TEXTURE30);
  MRB_ATTACH_CONST(TEXTURE31);
  MRB_ATTACH_CONST(ACTIVE_TEXTURE);

  MRB_ATTACH_CONST(REPEAT);
  MRB_ATTACH_CONST(CLAMP_TO_EDGE);
  MRB_ATTACH_CONST(MIRRORED_REPEAT);

  MRB_ATTACH_CONST(FLOAT_VEC2);
  MRB_ATTACH_CONST(FLOAT_VEC3);
  MRB_ATTACH_CONST(FLOAT_VEC4);
  MRB_ATTACH_CONST(INT_VEC2);
  MRB_ATTACH_CONST(INT_VEC3);
  MRB_ATTACH_CONST(INT_VEC4);
  MRB_ATTACH_CONST(BOOL);
  MRB_ATTACH_CONST(BOOL_VEC2);
  MRB_ATTACH_CONST(BOOL_VEC3);
  MRB_ATTACH_CONST(BOOL_VEC4);
  MRB_ATTACH_CONST(FLOAT_MAT2);
  MRB_ATTACH_CONST(FLOAT_MAT3);
  MRB_ATTACH_CONST(FLOAT_MAT4);
  MRB_ATTACH_CONST(SAMPLER_2D);
  MRB_ATTACH_CONST(SAMPLER_CUBE);

  MRB_ATTACH_CONST(VERTEX_ATTRIB_ARRAY_ENABLED);
  MRB_ATTACH_CONST(VERTEX_ATTRIB_ARRAY_SIZE);
  MRB_ATTACH_CONST(VERTEX_ATTRIB_ARRAY_STRIDE);
  MRB_ATTACH_CONST(VERTEX_ATTRIB_ARRAY_TYPE);
  MRB_ATTACH_CONST(VERTEX_ATTRIB_ARRAY_NORMALIZED);
  MRB_ATTACH_CONST(VERTEX_ATTRIB_ARRAY_POINTER);
  MRB_ATTACH_CONST(VERTEX_ATTRIB_ARRAY_BUFFER_BINDING);

  MRB_ATTACH_CONST(IMPLEMENTATION_COLOR_READ_TYPE);
  MRB_ATTACH_CONST(IMPLEMENTATION_COLOR_READ_FORMAT);

  MRB_ATTACH_CONST(COMPILE_STATUS);
  MRB_ATTACH_CONST(INFO_LOG_LENGTH);
  MRB_ATTACH_CONST(SHADER_SOURCE_LENGTH);
  MRB_ATTACH_CONST(SHADER_COMPILER);

  MRB_ATTACH_CONST(SHADER_BINARY_FORMATS);
  MRB_ATTACH_CONST(NUM_SHADER_BINARY_FORMATS);

  MRB_ATTACH_CONST(LOW_FLOAT);
  MRB_ATTACH_CONST(MEDIUM_FLOAT);
  MRB_ATTACH_CONST(HIGH_FLOAT);
  MRB_ATTACH_CONST(LOW_INT);
  MRB_ATTACH_CONST(MEDIUM_INT);
  MRB_ATTACH_CONST(HIGH_INT);

  MRB_ATTACH_CONST(FRAMEBUFFER);
  MRB_ATTACH_CONST(RENDERBUFFER);

  MRB_ATTACH_CONST(RGBA4);
  MRB_ATTACH_CONST(RGB5_A1);
  MRB_ATTACH_CONST(RGB565);
  MRB_ATTACH_CONST(DEPTH_COMPONENT16);
  MRB_ATTACH_CONST(STENCIL_INDEX);
  MRB_ATTACH_CONST(STENCIL_INDEX8);

  MRB_ATTACH_CONST(RENDERBUFFER_WIDTH);
  MRB_ATTACH_CONST(RENDERBUFFER_HEIGHT);
  MRB_ATTACH_CONST(RENDERBUFFER_INTERNAL_FORMAT);
  MRB_ATTACH_CONST(RENDERBUFFER_RED_SIZE);
  MRB_ATTACH_CONST(RENDERBUFFER_GREEN_SIZE);
  MRB_ATTACH_CONST(RENDERBUFFER_BLUE_SIZE);
  MRB_ATTACH_CONST(RENDERBUFFER_ALPHA_SIZE);
  MRB_ATTACH_CONST(RENDERBUFFER_DEPTH_SIZE);
  MRB_ATTACH_CONST(RENDERBUFFER_STENCIL_SIZE);

  MRB_ATTACH_CONST(FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE);
  MRB_ATTACH_CONST(FRAMEBUFFER_ATTACHMENT_OBJECT_NAME);
  MRB_ATTACH_CONST(FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL);
  MRB_ATTACH_CONST(FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE);

  MRB_ATTACH_CONST(COLOR_ATTACHMENT0);
  MRB_ATTACH_CONST(DEPTH_ATTACHMENT);
  MRB_ATTACH_CONST(STENCIL_ATTACHMENT);

  MRB_ATTACH_CONST(NONE);

  MRB_ATTACH_CONST(FRAMEBUFFER_COMPLETE);
  MRB_ATTACH_CONST(FRAMEBUFFER_INCOMPLETE_ATTACHMENT);
  MRB_ATTACH_CONST(FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT);
  MRB_ATTACH_CONST(FRAMEBUFFER_INCOMPLETE_DIMENSIONS);
  MRB_ATTACH_CONST(FRAMEBUFFER_UNSUPPORTED);

  MRB_ATTACH_CONST(FRAMEBUFFER_BINDING);
  MRB_ATTACH_CONST(RENDERBUFFER_BINDING);
  MRB_ATTACH_CONST(MAX_RENDERBUFFER_SIZE);

  MRB_ATTACH_CONST(INVALID_FRAMEBUFFER_OPERATION);

  /* GL core functions */
  MRB_ATTACH_FUNC(ActiveTexture, 1);
  MRB_ATTACH_FUNC(AttachShader, 2);
  MRB_ATTACH_FUNC(BindAttribLocation, 3);
  MRB_ATTACH_FUNC(BindBuffer, 2);
  MRB_ATTACH_FUNC(BindFramebuffer, 2);
  MRB_ATTACH_FUNC(BindRenderbuffer, 2);
  MRB_ATTACH_FUNC(BindTexture, 2);
  MRB_ATTACH_FUNC(BlendColor, 4);
  MRB_ATTACH_FUNC(BlendEquation, 1);
  MRB_ATTACH_FUNC(BlendEquationSeparate, 2);
  MRB_ATTACH_FUNC(BlendFunc, 2);
  MRB_ATTACH_FUNC(BlendFuncSeparate, 4);
  MRB_ATTACH_FUNC(BufferData, 4);
  MRB_ATTACH_FUNC(BufferSubData, 4);
  MRB_ATTACH_FUNC(CheckFramebufferStatus, 1);
  MRB_ATTACH_FUNC(Clear, 1);
  MRB_ATTACH_FUNC(ClearColor, 4);
  MRB_ATTACH_FUNC(ClearDepthf, 1);
  MRB_ATTACH_FUNC(ClearStencil, 1);
  MRB_ATTACH_FUNC(ColorMask, 4);
  MRB_ATTACH_FUNC(CompileShader, 1);
  MRB_ATTACH_FUNC(CompressedTexImage2D, 8);
  MRB_ATTACH_FUNC(CompressedTexSubImage2D, 9);
  MRB_ATTACH_FUNC(CopyTexImage2D, 8);
  MRB_ATTACH_FUNC(CopyTexSubImage2D, 8);
  MRB_ATTACH_FUNC(CreateProgram, 1);
  MRB_ATTACH_FUNC(CreateShader, 1);
  MRB_ATTACH_FUNC(CullFace, 1);
  MRB_ATTACH_FUNC(DeleteBuffers, 2);
  MRB_ATTACH_FUNC(DeleteFramebuffers, 2);
  MRB_ATTACH_FUNC(DeleteProgram, 1);
  MRB_ATTACH_FUNC(DeleteRenderbuffers, 2);
  MRB_ATTACH_FUNC(DeleteShader, 1);
  MRB_ATTACH_FUNC(DeleteTextures, 2);
  MRB_ATTACH_FUNC(DepthFunc, 1);
  MRB_ATTACH_FUNC(DepthMask, 1);
  MRB_ATTACH_FUNC(DepthRangef, 2);
  MRB_ATTACH_FUNC(DetachShader, 2);
  MRB_ATTACH_FUNC(Disable, 1);
  MRB_ATTACH_FUNC(DisableVertexAttribArray, 1);
  MRB_ATTACH_FUNC(DrawArrays, 3);
  MRB_ATTACH_FUNC(DrawElements, 4);
  MRB_ATTACH_FUNC(Enable, 1);
  MRB_ATTACH_FUNC(EnableVertexAttribArray, 1);
  MRB_ATTACH_FUNC(Finish, 1);
  MRB_ATTACH_FUNC(Flush, 1);
  MRB_ATTACH_FUNC(FramebufferRenderbuffer, 4);
  MRB_ATTACH_FUNC(FramebufferTexture2D, 5);
  MRB_ATTACH_FUNC(FrontFace, 1);
  MRB_ATTACH_FUNC(GenBuffers, 2);
  MRB_ATTACH_FUNC(GenerateMipmap, 1);
  MRB_ATTACH_FUNC(GenFramebuffers, 2);
  MRB_ATTACH_FUNC(GenRenderbuffers, 2);
  MRB_ATTACH_FUNC(GenTextures, 2);
  MRB_ATTACH_FUNC(GetActiveAttrib, 7);
  MRB_ATTACH_FUNC(GetActiveUniform, 7);

  /* TODO: Get* functions are a little complicated to handle, will come back later. */
  /* MRB_ATTACH_FUNC(GetAttachedShaders, 4); */
  /* MRB_ATTACH_FUNC(GetAttribLocation, 2); */
  /* MRB_ATTACH_FUNC(GetBooleanv, 2); */
  /* MRB_ATTACH_FUNC(GetBufferParameteriv, 3); */
  /* MRB_ATTACH_FUNC(GetError, 1); */
  /* MRB_ATTACH_FUNC(GetFloatv, 2); */
  /* MRB_ATTACH_FUNC(GetFramebufferAttachmentParameteriv, 4); */
  /* MRB_ATTACH_FUNC(GetIntegerv, 2); */
  /* MRB_ATTACH_FUNC(GetProgramiv, 3); */
  /* MRB_ATTACH_FUNC(GetProgramInfoLog, 4); */
  /* MRB_ATTACH_FUNC(GetRenderbufferParameteriv, 3); */
  /* MRB_ATTACH_FUNC(GetShaderiv, 3); */
  /* MRB_ATTACH_FUNC(GetShaderInfoLog, 4); */
  /* MRB_ATTACH_FUNC(GetShaderPrecisionFormat, 4); */
  /* MRB_ATTACH_FUNC(GetShaderSource, 4); */
  /* MRB_ATTACH_FUNC(GetString, 1); */
  /* MRB_ATTACH_FUNC(GetTexParameterfv, 3); */
  /* MRB_ATTACH_FUNC(GetTexParameteriv, 3); */
  /* MRB_ATTACH_FUNC(GetUniformfv, 3); */
  /* MRB_ATTACH_FUNC(GetUniformiv, 3); */
  /* MRB_ATTACH_FUNC(GetUniformLocation, 2); */
  /* MRB_ATTACH_FUNC(GetVertexAttribfv, 3); */
  /* MRB_ATTACH_FUNC(GetVertexAttribiv, 3); */
  /* MRB_ATTACH_FUNC(GetVertexAttribPointerv, 3); */

  MRB_ATTACH_FUNC(Hint, 2);
  MRB_ATTACH_FUNC(IsBuffer, 1);
  MRB_ATTACH_FUNC(IsEnabled, 1);
  MRB_ATTACH_FUNC(IsFramebuffer, 1);
  MRB_ATTACH_FUNC(IsProgram, 1);
  MRB_ATTACH_FUNC(IsRenderbuffer, 1);
  MRB_ATTACH_FUNC(IsShader, 1);
  MRB_ATTACH_FUNC(IsTexture, 1);
  MRB_ATTACH_FUNC(LineWidth, 1);
  MRB_ATTACH_FUNC(LinkProgram, 1);
  MRB_ATTACH_FUNC(PixelStorei, 2);
  MRB_ATTACH_FUNC(PolygonOffset, 2);

  /* MRB_ATTACH_FUNC(ReadPixels, 7); */

  MRB_ATTACH_FUNC(ReleaseShaderCompiler, 1);
  MRB_ATTACH_FUNC(RenderbufferStorage, 4);

  /* MRB_ATTACH_FUNC(SampleCoverage, 2); */
  /* MRB_ATTACH_FUNC(Scissor, 4); */
  /* MRB_ATTACH_FUNC(ShaderBinary, 5); */
  /* MRB_ATTACH_FUNC(ShaderSource, 4); */
  /* MRB_ATTACH_FUNC(StencilFunc, 3); */
  /* MRB_ATTACH_FUNC(StencilFuncSeparate, 4); */
  /* MRB_ATTACH_FUNC(StencilMask, 1); */
  /* MRB_ATTACH_FUNC(StencilMaskSeparate, 2); */
  /* MRB_ATTACH_FUNC(StencilOp, 3); */
  /* MRB_ATTACH_FUNC(StencilOpSeparate, 4); */
  /* MRB_ATTACH_FUNC(TexImage2D, 9); */
  /* MRB_ATTACH_FUNC(TexParameterf, 3); */
  /* MRB_ATTACH_FUNC(TexParameterfv, 3); */
  /* MRB_ATTACH_FUNC(TexParameteri, 3); */
  /* MRB_ATTACH_FUNC(TexParameteriv, 3); */
  /* MRB_ATTACH_FUNC(TexSubImage2D, 9); */
  /* MRB_ATTACH_FUNC(Uniform1f, 2); */
  /* MRB_ATTACH_FUNC(Uniform1fv, 3); */
  /* MRB_ATTACH_FUNC(Uniform1i, 2); */
  /* MRB_ATTACH_FUNC(Uniform1iv, 3); */
  /* MRB_ATTACH_FUNC(Uniform2f, 3); */
  /* MRB_ATTACH_FUNC(Uniform2fv, 3); */
  /* MRB_ATTACH_FUNC(Uniform2i, 3); */
  /* MRB_ATTACH_FUNC(Uniform2iv, 3); */
  /* MRB_ATTACH_FUNC(Uniform3f, 4); */
  /* MRB_ATTACH_FUNC(Uniform3fv, 3); */
  /* MRB_ATTACH_FUNC(Uniform3i, 4); */
  /* MRB_ATTACH_FUNC(Uniform3iv, 3); */
  /* MRB_ATTACH_FUNC(Uniform4f, 5); */
  /* MRB_ATTACH_FUNC(Uniform4fv, 3); */
  /* MRB_ATTACH_FUNC(Uniform4i, 5); */
  /* MRB_ATTACH_FUNC(Uniform4iv, 3); */
  /* MRB_ATTACH_FUNC(UniformMatrix2fv, 4); */
  /* MRB_ATTACH_FUNC(UniformMatrix3fv, 4); */
  /* MRB_ATTACH_FUNC(UniformMatrix4fv, 4); */
  /* MRB_ATTACH_FUNC(UseProgram, 1); */
  /* MRB_ATTACH_FUNC(ValidateProgram, 1); */
  /* MRB_ATTACH_FUNC(VertexAttrib1f, 2); */
  /* MRB_ATTACH_FUNC(VertexAttrib1fv, 2); */
  /* MRB_ATTACH_FUNC(VertexAttrib2f, 3); */
  /* MRB_ATTACH_FUNC(VertexAttrib2fv, 2); */
  /* MRB_ATTACH_FUNC(VertexAttrib3f, 4); */
  /* MRB_ATTACH_FUNC(VertexAttrib3fv, 2); */
  /* MRB_ATTACH_FUNC(VertexAttrib4f, 5); */
  /* MRB_ATTACH_FUNC(VertexAttrib4fv, 2); */
  /* MRB_ATTACH_FUNC(VertexAttribPointer, 6); */
  /* MRB_ATTACH_FUNC(Viewport, 4); */
}
